version: '3'

includes:
    frontend:
        taskfile: ./frontend/Taskfile.yml
        dir: ./frontend
        flatten: true
    backend:
        taskfile: ./backend/Taskfile.yml
        dir: ./backend
        flatten: true
    desktop:
        taskfile: ./desktop/Taskfile.yml
        dir: ./desktop

tasks:
    dev:
        desc: Start backend and frontend in parallel
        deps:
            - backend
            - frontend

    checkup:
        desc: Run all checks (lint, format, and tests)
        deps:
            - lint
            - format:check

    docker:
        desc: Build and run the local Docker image
        cmds:
            - docker compose -f docker-compose.local.yml up --build

    docker:stop:
        desc: Stop the local Docker container
        cmds:
            - docker compose -f docker-compose.local.yml down

    stats:
        desc: Count the amount of lines of code
        cmds:
            - cloc . --exclude-dir=dist,node_modules --not-match-f="(pnpm-lock|package-lock|yarn\.lock)"
