// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService exposes window chrome controls to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * HideTrafficLights hides the macOS traffic light window buttons (no-op on other platforms).
 */
export function HideTrafficLights(): $CancellablePromise<void> {
    return $Call.ByID(2240165063);
}

/**
 * IsFullscreen reports whether the window is currently fullscreen.
 */
export function IsFullscreen(): $CancellablePromise<boolean> {
    return $Call.ByID(1414357132);
}

/**
 * ShowTrafficLights restores the macOS traffic light window buttons (no-op on other platforms).
 */
export function ShowTrafficLights(): $CancellablePromise<void> {
    return $Call.ByID(3756487496);
}

/**
 * ToggleFullscreen toggles native window fullscreen.
 */
export function ToggleFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(954194204);
}
