import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import i18n from 'i18next';

export const SECTION_TITLE_TRANSLATIONS: Record<string, Record<string, string>> = {
    'top rated anime': {
        tr: 'En Yüksek Puanlı Animeler',
        en: 'Top Rated Anime',
        de: 'Bestbewertete Animes',
        fr: 'Animés les mieux notés',
        es: 'Anime mejor valorado',
        pt: 'Animes mais bem avaliados',
        sv: 'Topprankad anime',
        pl: 'Najwyżej oceniane anime',
        it: 'Anime più votati',
        ro: 'Anime cu cele mai mari evaluări',
        vi: 'Anime được đánh giá cao nhất',
        ja: '高評価のアニメ',
        zh: '最高评分动漫',
    },
    'recently released anime': {
        tr: 'Yeni Çıkan Animeler',
        en: 'Recently Released Anime',
        de: 'Kürzlich veröffentlichte Animes',
        fr: 'Animés récemment sortis',
        es: 'Anime lanzado recientemente',
        pt: 'Animes lançados recentemente',
        sv: 'Nyligen släppt anime',
        pl: 'Ostatnio wydane anime',
        it: 'Anime rilasciati di recente',
        ro: 'Anime lansate recent',
        vi: 'Anime mới phát hành',
        ja: '最近リリースされたアニメ',
        zh: '最近上映的动漫',
    },
    'recently released movies': {
        tr: 'Yeni Çıkan Filmler',
        en: 'Recently Released Movies',
        de: 'Kürzlich veröffentlichte Filme',
        fr: 'Films récemment sortis',
        es: 'Películas recién estrenadas',
        pt: 'Filmes lançados recentemente',
        sv: 'Nyligen släppta filmer',
        pl: 'Ostatnio wydane filmy',
        it: 'Film rilasciati di recente',
        ro: 'Filme lansate recent',
        vi: 'Phim mới phát hành',
        ja: '最近リリースされた映画',
        zh: '最近上映的电影',
    },
    'recently released': {
        tr: 'Yeni Çıkanlar',
        en: 'Recently Released',
        de: 'Kürzlich veröffentlicht',
        fr: 'Récemment sorti',
        es: 'Recién estrenado',
        pt: 'Lançado recentemente',
        sv: 'Nyligen släppt',
        pl: 'Ostatnio wydane',
        it: 'Rilasciato di recente',
        ro: 'Lansate recent',
        vi: 'Mới phát hành',
        ja: '最近リリース',
        zh: '最近发布',
    },
    'top rated': {
        tr: 'En Yüksek Puanlılar',
        en: 'Top Rated',
        de: 'Bestbewertet',
        fr: 'Les mieux notés',
        es: 'Mejor valorado',
        pt: 'Mais bem avaliados',
        sv: 'Topprankade',
        pl: 'Najwyżej oceniane',
        it: 'I più votati',
        ro: 'Cele mai mari evaluări',
        vi: 'Được đánh giá cao nhất',
        ja: '高評価',
        zh: '最高评分',
    },
    favorites: {
        tr: 'Favoriler',
        en: 'Favorites',
        de: 'Favoriten',
        fr: 'Favoris',
        es: 'Favoritos',
        pt: 'Favoritos',
        sv: 'Favoriter',
        pl: 'Ulubione',
        it: 'Preferiti',
        ro: 'Favorite',
        vi: 'Mục yêu thích',
        ja: 'お気に入り',
        zh: '收藏夹',
    },
    watchlist: {
        tr: 'İzleme Listesi',
        en: 'Watchlist',
        de: 'Merkliste',
        fr: 'Liste de lecture',
        es: 'Lista de seguimiento',
        pt: 'Lista de interesses',
        sv: 'Att se-lista',
        pl: 'Lista do obejrzenia',
        it: 'Lista di controllo',
        ro: 'Listă de vizionare',
        vi: 'Danh sách theo dõi',
        ja: 'ウォッチリスト',
        zh: '待播清单',
    },
    studios: {
        tr: 'Stüdyolar',
        en: 'Studios',
        de: 'Studios',
        fr: 'Studios',
        es: 'Estudios',
        pt: 'Estúdios',
        sv: 'Studior',
        pl: 'Studia',
        it: 'Studi',
        ro: 'Studiouri',
        vi: 'Hãng phim',
        ja: 'スタジオ',
        zh: '制片厂',
    },
    libraries: {
        tr: 'Kütüphaneler',
        en: 'Libraries',
        de: 'Bibliotheken',
        fr: 'Bibliothèques',
        es: 'Bibliotecas',
        pt: 'Bibliotecas',
        sv: 'Bibliotek',
        pl: 'Biblioteki',
        it: 'Librerie',
        ro: 'Biblioteci',
        vi: 'Thư viện',
        ja: 'ライブラリ',
        zh: '媒体库',
    },
    'continue watching': {
        tr: 'İzlemeye Devam Et',
        en: 'Continue Watching',
        de: 'Weiterschauen',
        fr: 'Reprendre la lecture',
        es: 'Continuar viendo',
        pt: 'Continuar assistindo',
        sv: 'Fortsätt titta',
        pl: 'Kontynuuj oglądanie',
        it: 'Continua a guardare',
        ro: 'Continuă vizionarea',
        vi: 'Tiếp tục xem',
        ja: '続きを視聴',
        zh: '继续观看',
    },
    'next up': {
        tr: 'Sıradaki',
        en: 'Next Up',
        de: 'Als Nächstes',
        fr: 'Suivant',
        es: 'A continuación',
        pt: 'A seguir',
        sv: 'Nästa',
        pl: 'Następne',
        it: 'Prossimo',
        ro: 'Urmează',
        vi: 'Tiếp theo',
        ja: '次を再生',
        zh: '接下来播放',
    },
    resume: {
        tr: 'Kaldığın Yerden Devam Et',
        en: 'Resume',
        de: 'Fortsetzen',
        fr: 'Reprendre',
        es: 'Reanudar',
        pt: 'Continuar',
        sv: 'Återuppta',
        pl: 'Wznów',
        it: 'Riprendi',
        ro: 'Reia',
        vi: 'Tiếp tục',
        ja: '再開',
        zh: '继续',
    },
    'recommended for you': {
        tr: 'Sizin İçin Önerilenler',
        en: 'Recommended for You',
        de: 'Für dich empfohlen',
        fr: 'Recommandé pour vous',
        es: 'Recomendado para ti',
        pt: 'Recomendado para você',
        sv: 'Rekommenderat för dig',
        pl: 'Polecane dla Ciebie',
        it: 'Consigliati per te',
        ro: 'Recomandat pentru tine',
        vi: 'Đề xuất cho bạn',
        ja: 'おすすめ',
        zh: '为您推荐',
    },
    genres: {
        tr: 'Türler',
        en: 'Genres',
        de: 'Genres',
        fr: 'Genres',
        es: 'Géneros',
        pt: 'Gêneros',
        sv: 'Genrer',
        pl: 'Gatunki',
        it: 'Generi',
        ro: 'Genuri',
        vi: 'Thể loại',
        ja: 'ジャンル',
        zh: '类型',
    },
    'recent episodes': {
        tr: 'Son Bölümler',
        en: 'Recent Episodes',
        de: 'Neueste Episoden',
        fr: 'Épisodes récents',
        es: 'Episodios recientes',
        pt: 'Episódios recentes',
        sv: 'Senaste avsnitten',
        pl: 'Najnowsze odcinki',
        it: 'Episodi recenti',
        ro: 'Episoade recente',
        vi: 'Tập gần đây',
        ja: '最近のエピソード',
        zh: '最新剧集',
    },
    trending: {
        tr: 'Trendler',
        en: 'Trending',
        de: 'Trends',
        fr: 'Tendances',
        es: 'Tendencias',
        pt: 'Em alta',
        sv: 'Populärt',
        pl: 'Na czasie',
        it: 'Di tendenza',
        ro: 'În tendințe',
        vi: 'Thịnh hành',
        ja: 'トレンド',
        zh: '趋势',
    },
    'popular movies': {
        tr: 'Popüler Filmler',
        en: 'Popular Movies',
        de: 'Beliebte Filme',
        fr: 'Films populaires',
        es: 'Películas populares',
        pt: 'Filmes populares',
        sv: 'Populära filmer',
        pl: 'Popularne filmy',
        it: 'Film popolari',
        ro: 'Filme populare',
        vi: 'Phim phổ biến',
        ja: '人気の映画',
        zh: '热门电影',
    },
    'popular series': {
        tr: 'Popüler Diziler',
        en: 'Popular Series',
        de: 'Beliebte Serien',
        fr: 'Séries populaires',
        es: 'Series populares',
        pt: 'Séries populares',
        sv: 'Populära serier',
        pl: 'Popularne seriale',
        it: 'Serie popolari',
        ro: 'Seriale populare',
        vi: 'Phim bộ phổ biến',
        ja: '人気のシリーズ',
        zh: '热门剧集',
    },
};

export function getTranslatedSectionTitle(title?: string, fallback?: string, lng?: string): string {
    const lang = (lng || i18n.language || 'en').split('-')[0].toLowerCase();

    if (title) {
        const key = title.trim().toLowerCase();
        const entry = SECTION_TITLE_TRANSLATIONS[key];
        if (entry) {
            return entry[lang] || entry['en'] || title;
        }
        return title;
    }

    if (fallback) {
        const key = fallback.trim().toLowerCase();
        const entry = SECTION_TITLE_TRANSLATIONS[key];
        if (entry) {
            return entry[lang] || entry['en'] || fallback;
        }
        return fallback;
    }

    return '';
}

export function useTranslatedSectionTitle() {
    const { i18n } = useTranslation();
    return useCallback(
        (title?: string, fallback?: string) => {
            return getTranslatedSectionTitle(title, fallback, i18n.language);
        },
        [i18n.language]
    );
}
